<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;


class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

     //Los Seeders se utilizan para inicializar la base de datos con datos de prueba que permiten 
     //comprobar la aplicación sin la necesidad de introducir manualmente grandes cantidades de información.
    public function run()
    {
        $datos = [
            array(
                'nombre' => "Café Caramel con Chocolate",
                'precio' => 2.00,
                'imagen' => "cafe_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Café Frio con Chocolate Grande",
                'precio' => 3.50,
                'imagen' => "cafe_02",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Latte Frio con Chocolate Grande",
                'precio' => 3.00,
                'imagen' => "cafe_03",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Latte Frio con Crema",
                'precio' => 2.00,
                'imagen' => "cafe_04",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Malteada Fria con Chocolate Grande",
                'precio' => 2.50,
                'imagen' => "cafe_05",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Café Mocha Caliente Pequeño",
                'precio' => 1.00,
                'imagen' => "cafe_06",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Café Mocha Caliente Grande con Chocolate",
                'precio' => 2.00,
                'imagen' => "cafe_07",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Café Caliente Capuchino Grande",
                'precio' => 3.00,
                'imagen' => "cafe_08",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Café Mocha Caliente Mediano",
                'precio' => 2.0,
                'imagen' => "cafe_09",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Café Mocha Frio con Caramelo Mediano",
                'precio' => 2.00,
                'imagen' => "cafe_10",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Café Mocha Frio con Chocolate Mediano",
                'precio' => 2.50,
                'imagen' => "cafe_11",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Café Espresso",
                'precio' => 1.50,
                'imagen' => "cafe_12",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Café Capuchino Grande con Caramelo",
                'precio' => 2.50,
                'imagen' => "cafe_13",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Café Caramelo Grande",
                'precio' => 3.50,
                'imagen' => "cafe_14",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete de 3 donas de Chocolate",
                'precio' => 4.50,
                'imagen' => "donas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete de 3 donas Glaseadas",
                'precio' => 4.50,
                'imagen' => "donas_02",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Dona de Fresa",
                'precio' => 1.50,
                'imagen' => "donas_03",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Dona con Galleta de Chocolate",
                'precio' => 2.50,
                'imagen' => "donas_04",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Dona glass con Chispas Sabor Fresa",
                'precio' => 1.50,
                'imagen' => "donas_05",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Dona glass con Chocolate",
                'precio' => 1.50,
                'imagen' => "donas_06",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Dona de Chocolate con MÁS Chocolate",
                'precio' => 2.00,
                'imagen' => "donas_07",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete de 3 donas de Chocolate",
                'precio' => 4.50,
                'imagen' => "donas_08",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete de 3 donas con Vainilla y Chocolate",
                'precio' => 4.50,
                'imagen' => "donas_09",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete de 6 Donas",
                'precio' => 5.00,
                'imagen' => "donas_10",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete de 3 Variadas",
                'precio' => 4.50,
                'imagen' => "donas_11",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Dona Natural con Chocolate",
                'precio' => 2.00,
                'imagen' => "donas_12",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete de 3 Donas de Chocolate con Chispas",
                'precio' => 4.00,
                'imagen' => "donas_13",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Dona Chocolate y Coco",
                'precio' => 2.00,
                'imagen' => "donas_14",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete Galletas de Chocolate",
                'precio' => 1.50,
                'imagen' => "galletas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete Galletas de Chocolate y Avena",
                'precio' => 1.50,
                'imagen' => "galletas_02",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete de Muffins de Vainilla",
                'precio' => 1.50,
                'imagen' => "galletas_03",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete de 4 Galletas de Avena",
                'precio' => 2.50,
                'imagen' => "galletas_04",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Galletas de Mantequilla Variadas",
                'precio' => 2.00,
                'imagen' => "galletas_05",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Galletas de sabores frutales",
                'precio' => 2.00,
                'imagen' => "galletas_06",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Hamburguesa Sencilla",
                'precio' => 6.00,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Hamburguesa de Pollo",
                'precio' => 5.50,
                'imagen' => "hamburguesas_02",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Hamburguesa de Pollo y Chili",
                'precio' => 5.00,
                'imagen' => "hamburguesas_03",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Hamburguesa Queso y Pepinos",
                'precio' => 5.50,
                'imagen' => "hamburguesas_04",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Hamburguesa Cuarto de Libra",
                'precio' => 6.00,
                'imagen' => "hamburguesas_05",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Hamburguesa Doble Queso",
                'precio' => 6.00,
                'imagen' => "hamburguesas_06",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Hot Dog Especial",
                'precio' => 5.00,
                'imagen' => "hamburguesas_07",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Paquete 2 Hot Dogs",
                'precio' => 7.00,
                'imagen' => "hamburguesas_08",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "4 Rebanadas de Pay de Queso",
                'precio' => 4.00,
                'imagen' => "pastel_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Waffle Especial",
                'precio' => 4.00,
                'imagen' => "pastel_02",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Croissants De la casa",
                'precio' => 3.00,
                'imagen' => "pastel_03",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pay de Queso",
                'precio' => 7.0,
                'imagen' => "pastel_04",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pastel de Chocolate",
                'precio' => 4.00,
                'imagen' => "pastel_05",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Rebanada Pastel de Chocolate",
                'precio' => 5.00,
                'imagen' => "pastel_06",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Spicy con Doble Queso",
                'precio' => 6.50,
                'imagen' => "pizzas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Jamón y Queso",
                'precio' => 6.50,
                'imagen' => "pizzas_02",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Doble Queso",
                'precio' => 7.00,
                'imagen' => "pizzas_03",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Especial de la Casa",
                'precio' => 7.00,
                'imagen' => "pizzas_04",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Chorizo",
                'precio' => 6.50,
                'imagen' => "pizzas_05",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Hawaiana",
                'precio' => 7.00,
                'imagen' => "pizzas_06",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Tocino",
                'precio' => 7.50,
                'imagen' => "pizzas_07",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Vegetales y Queso",
                'precio' => 6.50,
                'imagen' => "pizzas_08",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Pepperoni y Queso",
                'precio' => 7.00,
                'imagen' => "pizzas_09",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Aceitunas y Queso",
                'precio' => 6.50,
                'imagen' => "pizzas_10",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Pizza Queso, Jamón y Champiñones",
                'precio' => 6.00,
                'imagen' => "pizzas_11",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
        ];
        
        //Con esta linea de codigo insertaremos los datos
        DB::table('productos')->insert($datos);
    }
}